name: date_o_matic
description: "A mobile app that brings people together."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  package_info_plus: ^8.0.0
  bluetooth_low_energy: ^6.0.2
  permission_handler: ^12.0.0+1
  get_it: ^8.0.3
  injectable: ^2.3.2
  flutter_secure_storage: ^10.0.0-beta.4
  firebase_crashlytics: ^4.3.6
  firebase_core: ^3.13.1
  firebase_analytics: ^11.4.6
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  #  flutter_launcher_icons: any
  #  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_oss_licenses: ^3.0.2

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/Applogo.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
